# font — поменяй под себя
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 11.0

window_padding_width 8
confirm_os_window_close 0
enable_audio_bell no
scrollback_lines 10000

# remote control — чтобы Material You перекрашивал уже открытые окна
allow_remote_control yes
listen_on unix:/tmp/kitty

# цвета из pywal / kde-material-you-colors
include ~/.cache/wal/colors-kitty.conf

# прозрачность ПОСЛЕ include, иначе wal её затрёт
background_opacity 0.72
dynamic_background_opacity yes
